### ISSUE TITLE
Feature: Add mediaElements property to tangy-radio-blocks

### ISSUE THREAD

**Issue by chrisekelley** [Tangerine-Community/tangy-form#386]
Update 3/24/2023: 

We will create a tab interface for the form editor that enables the admin to assign sounds to form inputs. On left side will be a listing of sections and inputs, and right side will have a list of media elements that have been uploaded. Plus there will be a button to go to the upload media page, and also to reset the list and start over.

----

The following notes are obsolete.

Notes from chat 1/3/2023:

- Tangy radio blocks - we need image and sound to each option (optional) - see commit https://github.com/Tangerine-Community/tangy-form/commit/bb9b39d85f294cb489e7cbdb4a67ad99a2759b82
- we need on -load playing of sounds in order with highlighting of element that this sound is "attached". First we play all of the sounds that are attached, highlighting the element when it is played, and then when the user touches a radio button option, it also plays and highlights.
- we also need to be able to have two button at the bottom play instructions
- being able to dynamically modify the background per section 

background image value is a css variable but is not set-able: https://github.com/ICTatRTI/SE-tools/blob/main/client/form-b9c00566-1c80-4a39-bb9e-b0c8320f83e8/form.html#L200

**Comment by chrisekelley** [comment]
Issue: [#3473](https://github.com/Tangerine-Community/Tangerine/issues/3473)

**Comment by chrisekelley** [comment]
Moved to https://github.com/Tangerine-Community/tangy-form/issues/397

**Comment by esurface** [comment]
Closing - new strategy to be used - Replace with #410
